// others/PPT/vue3/src/components/SlideContent.vue
<script setup>
const props = defineProps({
  slide: { type: Object, required: true },
});
</script>

<template>
  <template v-if="slide.layout === 'cover'">
    <div class="cover__subtitle">{{ slide.subtitle }}</div>
    <div class="cover__meta">
      <span>{{ slide.meta }}</span>
    </div>
  </template>

  <template v-else>
    <template v-for="(block, i) in slide.blocks" :key="i">
      <div v-if="block.kind === 'cardHtml'" class="card" v-html="block.html"></div>

      <ul
        v-else-if="block.kind === 'list'"
        class="list"
        :class="{ cols2: block.columns === 2 }"
      >
        <li v-for="(item, idx) in block.items" :key="idx" v-html="item"></li>
      </ul>
    </template>
  </template>
</template>

// others/PPT/react/src/ui/SlideContent.jsx
export default function SlideContent({ slide }) {
  if (slide?.layout === "cover") {
    return (
      <>
        <div className="cover__subtitle">{slide.subtitle}</div>
        <div className="cover__meta">
          <span>{slide.meta}</span>
        </div>
      </>
    );
  }

  const blocks = slide?.blocks || [];
  return (
    <>
      {blocks.map((block, i) => {
        if (block.kind === "cardHtml") {
          return <div key={i} className="card" dangerouslySetInnerHTML={{ __html: block.html }} />;
        }

        if (block.kind === "list") {
          const cols2 = block.columns === 2;
          return (
            <ul key={i} className={`list ${cols2 ? "cols2" : ""}`}>
              {block.items.map((item, idx) => (
                <li key={idx} dangerouslySetInnerHTML={{ __html: item }} />
              ))}
            </ul>
          );
        }

        return null;
      })}
    </>
  );
}
